<?php

namespace HotelBundle\Repository;

/**
 * StayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StayRepository extends \Doctrine\ORM\EntityRepository
{
}
